### ISSUE TITLE
AI function is never called

### ISSUE THREAD

**Issue by ifuchs** [ethan-prime/Wordle-AI#1]
A function AI is defined but never called.

**Comment by ethan-prime** [comment]
This function isn’t crucial for it to function. It’s simply a function that repeats itself so I could collect data on how many tries it would take for the Bot to solve the puzzle. I should’ve removed it from the code before I published—my bad.

**Comment by ifuchs** [comment]
Thanks. I presume the same goes for the compare function which is only used by AI? Actually, would be nice to have it work just to play.

**Comment by ifuchs** [comment]
The bot could call whatever selection function you want to test.

**Comment by ifuchs** [comment]
I'm no expert in machine learning but it might be an interesting exercise to run one or another machine learning algo and have it find the best strategy.

**Comment by ethan-prime** [comment]
You’d probably be right; I’m not really well-versed in machine learning either. But yes, the compare function should be just for the bot. Sorry this code is kinda of a mess, I just whipped it up for myself one afternoon and this is what it came out to, lol

**Comment by ifuchs** [comment]
For your reading pleasure: https://arxiv.org/ftp/arxiv/papers/2202/2202.00557.pdf
